{
  imports = [
    #./todoman.nix
    ./obs.nix
    ./steam.nix
    ./fish
    ./hypr
    ./aerc.nix
    ./rbw.nix
    ./oama.nix
    ./vicinae.nix
    ./kdeconnect.nix
    ./mako.nix
    ./clipnotify.nix
    ./swayosd.nix
    ./jujutsu.nix
    ./zed.nix
    ./alacritty.nix
    ./helix.nix
    ./mail.nix
    ./wofi.nix
    ./fastfetch.nix
    ./git.nix
    ./waybar.nix
    ./neovim.nix
    ./starship.nix
    ./nushell.nix
    ./bat.nix
    ./eza.nix
    ./zsh.nix
    ./kitty.nix
    ./qutebrowser.nix
    ./opencode.nix
    ./hytale.nix
    ./caelestiaShell.nix
    ./quickshell/quickshell.nix
    ./brave.nix
  ];
}
