{
  imports = [
    ./kdeconnect.nix
    ./mako.nix
    ./fish.nix
    ./clipnotify.nix
    ./swayosd.nix
    ./jujutsu.nix
    ./zed.nix
    #./spicetify.nix
    #./nixvim # using NVF 
    ./alacritty.nix
    ./helix.nix
    ./gmail.nix
    ./wofi.nix
    ./nvf.nix
    ./fastfetch.nix
    ./hypr
    ./git.nix
    ./waybar.nix
    ./neovim.nix
    ./starship.nix
    ./nushell.nix
    ./bat.nix
    ./eza.nix
    ./zsh.nix
    ./kitty.nix
    ./qutebrowser.nix
    #./todoman.nix
  ];
}
