# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    ./extraHardwareOptions.nix  
    ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a5274005-99d5-4383-998c-33ae2233c689";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D874-93F7";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };
	
	fileSystems."/home/rakki/Mounts/ssd" = 
		{	device = "/dev/disk/by-uuid/5E42A95B42A93923";
			fsType = "ntfs";
			options = [ "rw" "uid=1000" "nofail" ];
		};

	fileSystems."/home/rakki/Mounts/nvme" = 
		{	device = "/dev/disk/by-uuid/01DA679184F3A5D0";
			fsType = "ntfs";
			options = [ "rw" "uid=1000" "nofail" ];
		};

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
