{
  imports = [
    ./obs.nix
    ./steam.nix
    ./fish
    ./hypr
    ./rbw.nix
    ./mako.nix
    ./clipnotify.nix
    ./swayosd.nix
    ./jujutsu.nix
    ./zed.nix
    ./alacritty.nix
    ./helix.nix
    ./calendar.nix
    ./wofi.nix
    ./fastfetch.nix
    ./git.nix
    ./waybar.nix
    ./neovim.nix
    ./starship.nix
    ./bat.nix
    ./eza.nix
    ./kitty.nix
    ./qutebrowser.nix
    ./opencode
    ./hytale.nix
    ./quickshell/quickshell.nix
    ./river.nix
    ./fuzzel.nix
    ./noctalia.nix
    ./spicetify.nix
    ./mangohud.nix
    ./firefox.nix
  ];
}
